### ISSUE TITLE
[BUG] - Frontend Search Results Page Recipe Bookmark Button Not Working When Not Logged In

### ISSUE THREAD

**Issue by jasonlaiys** [cs130-w21/12#112]
## Description
When not logged in and trying to bookmark a recipe in the search results page, the pop up appears for half a second and then disappears. This issue does not happen in the recipe detail page.

## Steps to Reproduce
Steps to reproduce the bug:
- [x] Step 1: Stay logged out
- [x] Step 2: Search for recipes
- [x] Step 3: Click on bookmark icon on any of the recipe cards

## Expected Behavior
The pop up should not disappear after half a second. It should remain intact until user clicks away.

**Comment by spencer-jin** [comment]
This bug is not observable in the local development environment, need to research why that happens on the deployed one
