### ISSUE TITLE
[BUG] - LOGIN / SIGN UP doesn't work on the deployed site

### ISSUE THREAD

**Issue by JakinHuangWang** [cs130-w21/12#114]
## Description
When trying to access the LOGIN / SIGN UP button through the deployed site, the login page gives **ERROR 400**

## Steps to Reproduce
Steps to reproduce the bug:
- [ ] Go to the deployed site: https://cuisinemachine.herokuapp.com/
- [ ] Press the LOGIN / SIGN UP button in the header
- [ ] It should redirect you to an ERROR 400

## Expected Behavior
The **ERROR 400** should not appear, instead it should present the users with a login form.

## Relevant screenshots
<img width="1440" alt="Screen Shot 2021-03-05 at 12 44 08 AM" src="https://user-images.githubusercontent.com/31380172/110090230-e7359600-7d4b-11eb-85c0-92dba5a1f804.png">

**Comment by spencer-jin** [comment]
fixed
