### ISSUE TITLE
Profile Page UI

### ISSUE THREAD

**Issue by JakinHuangWang** [cs130-w21/12#26]
## User Story
As a **user**, I should be able to **have an easy-to-use profile page** to **access and modify my data** so that **I enjoy using the web app**.

## Detailed Description
Users should be able to change their profile information on this page easily and intuitively.

## Acceptance Criteria
- [x] User should be able to change their email and password.
- [x] User should be able to change their name.
- [x] User should be able to change their profile photo.

**Comment by seoyoon-jin221** [comment]
This includes following tasks: 
[] #30 Social Media Login
[] #15 Delete Profile 
[] #16 Change Password 
[] #17 Change email

**Comment by seoyoon-jin221** [comment]
User Story
As a User, I would like a profile management page so that we can manage profile data.

Detailed Description
Provide additional details and context.

Acceptance Criteria
